route:
  receiver: "oncall"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "oncall"
    webhook_configs:
      - url: http://host.docker.internal:8080/integrations/v1/alertmanager/sRLYtJ4UeFwaqHcajMyQHFuU6/ # Lấy từ Bước 1: Link URL Integration của Alert Manager
        send_resolved: true
        max_alerts: 100